name: Build Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      - name: Build and tag Docker Image
        run: |
          docker build -t repo/app-name:123 \
          -f Dockerfile .
      - name: Generating Artifact 
        run: |
          printf '{
            "image": "repo/app-name:123"
          }' >> context.json
      - uses: actions/upload-artifact@v3
        with:
          name: context
          path: ./

  share-artifact:
    permissions: 
      actions: read
    needs: build
    uses: ./.github/workflows/get-artifact.yml