name: Build Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

  codeql:
    permissions: 
      actions: read
      contents: read
      security-events: write
    needs: build
    uses: ./.github/workflows/codeql-test.yml