name: Get artifact 

permissions:
  actions: read

on: workflow_call

jobs:
  get-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact from repository
        uses: actions/download-artifact@v3
        with: 
          name: context
          path: ./
      - name: test
        run: cd context && ls