name: Get artifact 

permissions:
  actions: read

on: workflow_call

jobs:
  get-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow_conclusion: success
          name: context
          check_artifacts: true
          if_no_artifact_found: warn
      - name: Test
        run: cat context.json
      - name: Return Parsed JSON
        run: |
          echo 'context.json<<EOF' >> $GITHUB_ENV
          cat context.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name:
        run: |
          echo '${{ fromJson(env.PACKAGE_JSON).image }}'