name: Get artifact 

on: workflow_call

jobs:
  get-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact from repository
        uses: actions/download-artifact@v3
          with: 
            name: context.zip
            path: ./
      - name: Unzip file
        run: unzip context.zip
      - name: Return Parsed JSON
        run: |
          echo 'context.json<<EOF' >> $GITHUB_ENV
          cat context.zip/context.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        run: |
          echo '${{ fromJson(env.PACKAGE_JSON).image }}'