name: Get artifact 

permissions:
  actions: read

on: workflow_call

jobs:
  get-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow_conclusion: success
          name: context
          check_artifacts: true
          if_no_artifact_found: warn
      - name: Test
        run: cat context.json
      - name: Install jq
        uses: sergeysova/jq-action@v2
        with:
          tool: jq
          version: '3.7'
      - name: Get value from JSON
        run: echo $(jq '.image' ./context.json)